# Generated by Django 5.0.6 on 2024-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='c', upload_to='images/'),
            preserve_default=False,
        ),
    ]
